services:
  api:
    build:
      context: apps/api
      dockerfile: Dockerfile
    ports:
      - "3010:3000"

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
